// ── MedAI Platform: Demo Data ──

import type {
  Patient,
  Appointment,
  ClinicalNote,
  IntakeForm,
  Prescription,
  HealthcareMetric,
} from "./types";

// ── 12 Patients ──
export const patients: Patient[] = [
  {
    id: "p01",
    firstName: "Maria",
    lastName: "Santos",
    dob: "1967-04-12",
    email: "maria.santos@email.com",
    phone: "555-0101",
    status: "active",
    primaryPhysician: "Dr. Chen",
    lastVisit: "2026-06-08",
    conditions: ["Hypertension", "Type 2 Diabetes"],
    insuranceProvider: "BlueCross Premier",
    insuranceId: "BCP-882341",
    intakeCompleted: true,
    createdAt: "2025-01-15",
  },
  {
    id: "p02",
    firstName: "James",
    lastName: "Walker",
    dob: "1982-11-23",
    email: "j.walker@email.com",
    phone: "555-0102",
    status: "active",
    primaryPhysician: "Dr. Patel",
    lastVisit: "2026-06-07",
    conditions: ["Asthma", "Allergic Rhinitis"],
    insuranceProvider: "Aetna Health",
    insuranceId: "AH-445112",
    intakeCompleted: true,
    createdAt: "2025-03-02",
  },
  {
    id: "p03",
    firstName: "Elena",
    lastName: "Rodriguez",
    dob: "1991-07-30",
    email: "elena.r@email.com",
    phone: "555-0103",
    status: "active",
    primaryPhysician: "Dr. Chen",
    lastVisit: "2026-06-01",
    conditions: ["Migraine", "Anxiety"],
    insuranceProvider: "Cigna Connect",
    insuranceId: "CC-771990",
    intakeCompleted: false,
    createdAt: "2025-06-10",
  },
  {
    id: "p04",
    firstName: "Robert",
    lastName: "Kim",
    dob: "1955-02-18",
    email: "r.kim@email.com",
    phone: "555-0104",
    status: "on-hold",
    primaryPhysician: "Dr. Patel",
    lastVisit: "2026-05-20",
    conditions: ["Coronary Artery Disease", "Hyperlipidemia", "Osteoarthritis"],
    insuranceProvider: "Medicare Plus",
    insuranceId: "MP-332887",
    intakeCompleted: true,
    createdAt: "2024-09-01",
  },
  {
    id: "p05",
    firstName: "Sophia",
    lastName: "Nguyen",
    dob: "2003-12-05",
    email: "sophia.n@email.com",
    phone: "555-0105",
    status: "active",
    primaryPhysician: "Dr. Osei",
    lastVisit: "2026-06-06",
    conditions: ["Eczema", "Food Allergy"],
    insuranceProvider: "BlueCross Premier",
    insuranceId: "BCP-991203",
    intakeCompleted: true,
    createdAt: "2025-11-20",
  },
  {
    id: "p06",
    firstName: "David",
    lastName: "Thompson",
    dob: "1975-09-14",
    email: "d.thompson@email.com",
    phone: "555-0106",
    status: "active",
    primaryPhysician: "Dr. Osei",
    lastVisit: "2026-05-28",
    conditions: ["Lower Back Pain", "Insomnia"],
    insuranceProvider: "Aetna Health",
    insuranceId: "AH-552341",
    intakeCompleted: true,
    createdAt: "2025-04-18",
  },
  {
    id: "p07",
    firstName: "Amara",
    lastName: "Okafor",
    dob: "1988-03-22",
    email: "a.okafor@email.com",
    phone: "555-0107",
    status: "active",
    primaryPhysician: "Dr. Chen",
    lastVisit: "2026-06-09",
    conditions: ["Pregnancy (2nd Trimester)", "Iron Deficiency"],
    insuranceProvider: "Cigna Connect",
    insuranceId: "CC-883420",
    intakeCompleted: true,
    createdAt: "2026-01-05",
  },
  {
    id: "p08",
    firstName: "William",
    lastName: "Harrison",
    dob: "1948-08-11",
    email: "w.harrison@email.com",
    phone: "555-0108",
    status: "active",
    primaryPhysician: "Dr. Patel",
    lastVisit: "2026-06-04",
    conditions: ["COPD", "Hypertension", "Cataracts"],
    insuranceProvider: "Medicare Plus",
    insuranceId: "MP-118743",
    intakeCompleted: false,
    createdAt: "2024-06-15",
  },
  {
    id: "p09",
    firstName: "Lily",
    lastName: "Chen",
    dob: "2019-05-30",
    email: "lily.chen.parent@email.com",
    phone: "555-0109",
    status: "active",
    primaryPhysician: "Dr. Osei",
    lastVisit: "2026-06-03",
    conditions: ["Asthma", "Seasonal Allergies"],
    insuranceProvider: "BlueCross Premier",
    insuranceId: "BCP-445678",
    intakeCompleted: true,
    createdAt: "2025-08-12",
  },
  {
    id: "p10",
    firstName: "Michael",
    lastName: "Patel",
    dob: "1995-01-27",
    email: "m.patel@email.com",
    phone: "555-0110",
    status: "active",
    primaryPhysician: "Dr. Chen",
    lastVisit: "2026-06-02",
    conditions: ["Anxiety", "GERD"],
    insuranceProvider: "Aetna Health",
    insuranceId: "AH-778299",
    intakeCompleted: true,
    createdAt: "2025-07-30",
  },
  {
    id: "p11",
    firstName: "Grace",
    lastName: "Osei",
    dob: "1972-10-08",
    email: "g.osei@email.com",
    phone: "555-0111",
    status: "inactive",
    primaryPhysician: "Dr. Patel",
    lastVisit: "2025-12-15",
    conditions: ["Hypothyroidism", "Fibromyalgia"],
    insuranceProvider: "Cigna Connect",
    insuranceId: "CC-334215",
    intakeCompleted: true,
    createdAt: "2024-03-10",
  },
  {
    id: "p12",
    firstName: "Daniel",
    lastName: "Foster",
    dob: "2001-06-19",
    email: "d.foster@email.com",
    phone: "555-0112",
    status: "discharged",
    primaryPhysician: "Dr. Osei",
    lastVisit: "2026-04-30",
    conditions: ["Post-Surgical Recovery", "PT Follow-up"],
    insuranceProvider: "BlueCross Premier",
    insuranceId: "BCP-667891",
    intakeCompleted: true,
    createdAt: "2026-02-14",
  },
];

// ── 15 Appointments ──
export const appointments: Appointment[] = [
  {
    id: "a01",
    patientId: "p01",
    patientName: "Maria Santos",
    type: "checkup",
    status: "checked-in",
    date: "2026-06-09",
    time: "09:00",
    duration: 30,
    physician: "Dr. Chen",
    reason: "Blood pressure follow-up, diabetes maintenance",
    notesGenerated: false,
    createdAt: "2026-05-25",
  },
  {
    id: "a02",
    patientId: "p07",
    patientName: "Amara Okafor",
    type: "checkup",
    status: "in-progress",
    date: "2026-06-09",
    time: "09:30",
    duration: 45,
    physician: "Dr. Chen",
    reason: "Prenatal checkup — 22 week visit",
    notesGenerated: false,
    createdAt: "2026-05-20",
  },
  {
    id: "a03",
    patientId: "p03",
    patientName: "Elena Rodriguez",
    type: "follow-up",
    status: "scheduled",
    date: "2026-06-09",
    time: "10:15",
    duration: 30,
    physician: "Dr. Chen",
    reason: "Migraine treatment plan review",
    notesGenerated: false,
    createdAt: "2026-05-28",
  },
  {
    id: "a04",
    patientId: "p05",
    patientName: "Sophia Nguyen",
    type: "specialist",
    status: "scheduled",
    date: "2026-06-09",
    time: "11:00",
    duration: 60,
    physician: "Dr. Osei",
    reason: "Dermatology consult — eczema flare-up",
    notesGenerated: false,
    createdAt: "2026-05-18",
  },
  {
    id: "a05",
    patientId: "p08",
    patientName: "William Harrison",
    type: "checkup",
    status: "scheduled",
    date: "2026-06-09",
    time: "13:00",
    duration: 30,
    physician: "Dr. Patel",
    reason: "COPD management, medication review",
    notesGenerated: false,
    createdAt: "2026-06-01",
  },
  {
    id: "a06",
    patientId: "p10",
    patientName: "Michael Patel",
    type: "telehealth",
    status: "scheduled",
    date: "2026-06-09",
    time: "14:00",
    duration: 30,
    physician: "Dr. Chen",
    reason: "Anxiety medication adjustment, GERD follow-up",
    notesGenerated: false,
    createdAt: "2026-06-02",
  },
  {
    id: "a07",
    patientId: "p02",
    patientName: "James Walker",
    type: "follow-up",
    status: "completed",
    date: "2026-06-08",
    time: "09:00",
    duration: 30,
    physician: "Dr. Patel",
    reason: "Asthma control assessment",
    notesGenerated: true,
    createdAt: "2026-05-22",
  },
  {
    id: "a08",
    patientId: "p06",
    patientName: "David Thompson",
    type: "follow-up",
    status: "completed",
    date: "2026-06-07",
    time: "10:00",
    duration: 30,
    physician: "Dr. Osei",
    reason: "Lower back pain — physical therapy progress",
    notesGenerated: true,
    createdAt: "2026-05-15",
  },
  {
    id: "a09",
    patientId: "p04",
    patientName: "Robert Kim",
    type: "specialist",
    status: "completed",
    date: "2026-06-05",
    time: "11:00",
    duration: 45,
    physician: "Dr. Patel",
    reason: "Cardiology follow-up — lipid panel review",
    notesGenerated: true,
    createdAt: "2026-05-10",
  },
  {
    id: "a10",
    patientId: "p09",
    patientName: "Lily Chen",
    type: "checkup",
    status: "completed",
    date: "2026-06-03",
    time: "14:00",
    duration: 30,
    physician: "Dr. Osei",
    reason: "Pediatric asthma checkup",
    notesGenerated: true,
    createdAt: "2026-05-19",
  },
  {
    id: "a11",
    patientId: "p01",
    patientName: "Maria Santos",
    type: "follow-up",
    status: "completed",
    date: "2026-06-01",
    time: "09:30",
    duration: 30,
    physician: "Dr. Chen",
    reason: "Diabetes A1C review",
    notesGenerated: true,
    createdAt: "2026-05-12",
  },
  {
    id: "a12",
    patientId: "p03",
    patientName: "Elena Rodriguez",
    type: "follow-up",
    status: "completed",
    date: "2026-05-28",
    time: "15:00",
    duration: 30,
    physician: "Dr. Chen",
    reason: "Anxiety management — CBT progress",
    notesGenerated: true,
    createdAt: "2026-05-01",
  },
  {
    id: "a13",
    patientId: "p02",
    patientName: "James Walker",
    type: "urgent",
    status: "completed",
    date: "2026-05-25",
    time: "08:00",
    duration: 30,
    physician: "Dr. Patel",
    reason: "Acute asthma exacerbation",
    notesGenerated: true,
    createdAt: "2026-05-25",
  },
  {
    id: "a14",
    patientId: "p05",
    patientName: "Sophia Nguyen",
    type: "telehealth",
    status: "no-show",
    date: "2026-06-07",
    time: "16:00",
    duration: 30,
    physician: "Dr. Osei",
    reason: "Allergy medication refill",
    notesGenerated: false,
    createdAt: "2026-05-30",
  },
  {
    id: "a15",
    patientId: "p11",
    patientName: "Grace Osei",
    type: "checkup",
    status: "cancelled",
    date: "2026-06-10",
    time: "10:00",
    duration: 30,
    physician: "Dr. Patel",
    reason: "Thyroid panel review",
    notesGenerated: false,
    createdAt: "2026-05-28",
  },
];

// ── 10 Clinical Notes ──
export const clinicalNotes: ClinicalNote[] = [
  {
    id: "n01",
    appointmentId: "a07",
    patientId: "p02",
    patientName: "James Walker",
    date: "2026-06-08",
    physician: "Dr. Patel",
    transcriptPreview:
      "Patient reports mild wheezing during exercise but no nighttime symptoms. Using rescue inhaler 1-2 times per week...",
    aiSummary:
      "Asthma well-controlled on current regimen. PEFR 85% of predicted. Continue Symbicort 160/4.5 BID. No medication changes needed. Follow up in 3 months or sooner if symptoms worsen.",
    diagnosis: ["J45.909", "J30.9"],
    prescriptions: ["rx02"],
    followUpNeeded: true,
    followUpDate: "2026-09-08",
    status: "finalized",
    createdAt: "2026-06-08",
  },
  {
    id: "n02",
    appointmentId: "a08",
    patientId: "p06",
    patientName: "David Thompson",
    date: "2026-06-07",
    physician: "Dr. Osei",
    transcriptPreview:
      "Patient has completed 8 weeks of PT. Reports 60% reduction in lower back pain. No radicular symptoms. Sleeping better...",
    aiSummary:
      "Significant improvement in chronic lower back pain with physical therapy. Pain scale reduced from 7/10 to 3/10. Continue PT for 4 more weeks. Consider tapering cyclobenzaprine. Return to work clearance discussed.",
    diagnosis: ["M54.5"],
    prescriptions: ["rx04"],
    followUpNeeded: true,
    followUpDate: "2026-07-07",
    status: "finalized",
    createdAt: "2026-06-07",
  },
  {
    id: "n03",
    appointmentId: "a09",
    patientId: "p04",
    patientName: "Robert Kim",
    date: "2026-06-05",
    physician: "Dr. Patel",
    transcriptPreview:
      "Lipid panel results: Total cholesterol 210, LDL 138, HDL 42, Triglycerides 150. Patient adherent to statin therapy...",
    aiSummary:
      "Lipid profile shows modest improvement. LDL decreased from 155 to 138 on atorvastatin 20mg. Consider increasing to 40mg. Continue aspirin 81mg, BP controlled. Schedule repeat lipids in 12 weeks.",
    diagnosis: ["I25.10", "E78.5", "M19.90"],
    prescriptions: ["rx01", "rx03"],
    followUpNeeded: true,
    followUpDate: "2026-09-05",
    status: "finalized",
    createdAt: "2026-06-05",
  },
  {
    id: "n04",
    appointmentId: "a10",
    patientId: "p09",
    patientName: "Lily Chen",
    date: "2026-06-03",
    physician: "Dr. Osei",
    transcriptPreview:
      "Parent reports Lily had 1 mild asthma episode this month, resolved with albuterol. No school absences. Growth on track...",
    aiSummary:
      "Pediatric asthma well-controlled. Growth parameters at 65th percentile. Continue fluticasone 44mcg BID via spacer. Update asthma action plan for school. Annual flu vaccine recommended.",
    diagnosis: ["J45.30", "J30.2"],
    prescriptions: ["rx05"],
    followUpNeeded: true,
    followUpDate: "2026-09-03",
    status: "finalized",
    createdAt: "2026-06-03",
  },
  {
    id: "n05",
    appointmentId: "a11",
    patientId: "p01",
    patientName: "Maria Santos",
    date: "2026-06-01",
    physician: "Dr. Chen",
    transcriptPreview:
      "A1C result: 7.1%, down from 7.8%. Patient reports improved diet adherence. BP 128/82. No hypoglycemic episodes...",
    aiSummary:
      "A1C improved by 0.7 points with current metformin 1000mg BID and lifestyle changes. BP at target on lisinopril 10mg. Continue current regimen. Reinforce dietary counseling. Foot exam unremarkable.",
    diagnosis: ["E11.65", "I10"],
    prescriptions: ["rx06", "rx07"],
    followUpNeeded: true,
    followUpDate: "2026-09-01",
    status: "finalized",
    createdAt: "2026-06-01",
  },
  {
    id: "n06",
    appointmentId: "a13",
    patientId: "p02",
    patientName: "James Walker",
    date: "2026-05-25",
    physician: "Dr. Patel",
    transcriptPreview:
      "Patient presented with acute shortness of breath and wheezing. O2 sat 91% on room air. PEFR 55% predicted...",
    aiSummary:
      "Acute asthma exacerbation triggered by seasonal allergens. Treated with nebulized albuterol/ipratropium in clinic with good response. Prescribed prednisone 40mg taper x5 days. Follow up in 48 hours. Discussed trigger avoidance.",
    diagnosis: ["J45.901"],
    prescriptions: ["rx02", "rx08"],
    followUpNeeded: true,
    followUpDate: "2026-05-27",
    status: "finalized",
    createdAt: "2026-05-25",
  },
  {
    id: "n07",
    appointmentId: "a12",
    patientId: "p03",
    patientName: "Elena Rodriguez",
    date: "2026-05-28",
    physician: "Dr. Chen",
    transcriptPreview:
      "Patient has completed 12 CBT sessions. GAD-7 score dropped from 15 to 7. Migraine frequency reduced from 8 to 3 per month...",
    aiSummary:
      "Significant improvement in anxiety and migraine frequency with combination therapy (escitalopram 10mg + CBT). Continue current regimen. Discussed migraine trigger journal. Recommend neurologist consult for preventive options.",
    diagnosis: ["F41.1", "G43.909"],
    prescriptions: ["rx09"],
    followUpNeeded: true,
    followUpDate: "2026-08-28",
    status: "reviewed",
    createdAt: "2026-05-28",
  },
  {
    id: "n08",
    appointmentId: "a05",
    patientId: "p08",
    patientName: "William Harrison",
    date: "2026-06-02",
    physician: "Dr. Patel",
    transcriptPreview:
      "Patient reports increased shortness of breath on exertion. Using oxygen 2L at night. CAT score: 18...",
    aiSummary:
      "COPD with moderate exacerbation risk. CAT score 18 indicates high impact. Lung function: FEV1 55% predicted. Adjust tiotropium to 18mcg daily, add as-needed albuterol. Discuss pulmonary rehab referral.",
    diagnosis: ["J44.9", "I10", "H25.9"],
    prescriptions: ["rx10", "rx11"],
    followUpNeeded: true,
    followUpDate: "2026-07-01",
    status: "draft",
    aiSafetyReview: {
      riskLevel: "high",
      clinicianEdited: false,
      errorReportStatus: "queued",
      sourceAnchors: ["Transcript: CAT score 18", "Transcript: FEV1 55% predicted"],
      reviewNote:
        "Draft contains therapy escalation and pulmonary rehab guidance; require clinician verification before signing to catch possible ambient-scribe hallucinations.",
    },
    createdAt: "2026-06-02",
  },
  {
    id: "n09",
    appointmentId: "a02",
    patientId: "p07",
    patientName: "Amara Okafor",
    date: "2026-06-09",
    physician: "Dr. Chen",
    transcriptPreview:
      "22-week prenatal visit. Fetal heart rate 148 bpm. Fundal height 22 cm. Patient reports good fetal movement...",
    aiSummary:
      "Pregnancy progressing normally at 22 weeks. Anatomy scan results normal. Iron supplements continue for mild anemia (Hgb 10.8). Recommend glucose tolerance test at next visit. Discussed birth plan options.",
    diagnosis: ["Z34.80", "D50.9"],
    prescriptions: ["rx12"],
    followUpNeeded: true,
    followUpDate: "2026-07-09",
    status: "draft",
    aiSafetyReview: {
      riskLevel: "moderate",
      clinicianEdited: false,
      errorReportStatus: "queued",
      sourceAnchors: ["Transcript: fetal heart rate 148 bpm", "Transcript: Hgb 10.8"],
      reviewNote:
        "Prenatal summary is queued for sign-off because labs and follow-up timing should be reconciled against source transcript anchors.",
    },
    createdAt: "2026-06-09",
  },
  {
    id: "n10",
    appointmentId: "a06",
    patientId: "p10",
    patientName: "Michael Patel",
    date: "2026-06-06",
    physician: "Dr. Chen",
    transcriptPreview:
      "Telehealth visit. Patient reports increased work stress. Anxiety manageable but GERD symptoms worsening in evening...",
    aiSummary:
      "Anxiety stable on escitalopram 10mg. GERD symptoms suggest need for medication adjustment. Add famotidine 20mg at bedtime. Continue PPI in AM. Stress management techniques reviewed. Follow up in 6 weeks.",
    diagnosis: ["F41.9", "K21.9"],
    prescriptions: ["rx09", "rx13"],
    followUpNeeded: true,
    followUpDate: "2026-07-18",
    status: "draft",
    createdAt: "2026-06-06",
  },
];

// ── Intake Forms ──
export const intakeForms: IntakeForm[] = [
  {
    id: "if01",
    patientId: "p03",
    patientName: "Elena Rodriguez",
    status: "pending",
    submittedDate: null,
    sections: [
      { name: "demographics", label: "Demographics", completed: false },
      { name: "medical-history", label: "Medical History", completed: false },
      { name: "medications", label: "Current Medications", completed: false },
      { name: "allergies", label: "Allergies", completed: false },
      { name: "consent", label: "Consent & HIPAA", completed: false },
    ],
    aiFlagged: false,
    flaggedItems: [],
    createdAt: "2026-05-28",
  },
  {
    id: "if02",
    patientId: "p08",
    patientName: "William Harrison",
    status: "in-progress",
    submittedDate: null,
    sections: [
      { name: "demographics", label: "Demographics", completed: true },
      { name: "medical-history", label: "Medical History", completed: true },
      { name: "medications", label: "Current Medications", completed: false },
      { name: "allergies", label: "Allergies", completed: true },
      { name: "consent", label: "Consent & HIPAA", completed: false },
    ],
    aiFlagged: false,
    flaggedItems: [],
    createdAt: "2026-06-01",
  },
  {
    id: "if03",
    patientId: "p01",
    patientName: "Maria Santos",
    status: "completed",
    submittedDate: "2025-01-14",
    sections: [
      { name: "demographics", label: "Demographics", completed: true },
      { name: "medical-history", label: "Medical History", completed: true },
      { name: "medications", label: "Current Medications", completed: true },
      { name: "allergies", label: "Allergies", completed: true },
      { name: "consent", label: "Consent & HIPAA", completed: true },
    ],
    aiFlagged: false,
    flaggedItems: [],
    createdAt: "2025-01-10",
  },
  {
    id: "if04",
    patientId: "p02",
    patientName: "James Walker",
    status: "completed",
    submittedDate: "2025-02-28",
    sections: [
      { name: "demographics", label: "Demographics", completed: true },
      { name: "medical-history", label: "Medical History", completed: true },
      { name: "medications", label: "Current Medications", completed: true },
      { name: "allergies", label: "Allergies", completed: true },
      { name: "consent", label: "Consent & HIPAA", completed: true },
    ],
    aiFlagged: false,
    flaggedItems: [],
    createdAt: "2025-02-25",
  },
  {
    id: "if05",
    patientId: "p04",
    patientName: "Robert Kim",
    status: "needs-review",
    submittedDate: "2026-06-08",
    sections: [
      { name: "demographics", label: "Demographics", completed: true },
      { name: "medical-history", label: "Medical History", completed: true },
      { name: "medications", label: "Current Medications", completed: true },
      { name: "allergies", label: "Allergies", completed: true },
      { name: "consent", label: "Consent & HIPAA", completed: true },
    ],
    aiFlagged: true,
    flaggedItems: [
      "Possible drug interaction: warfarin + NSAID",
      "Missing surgical history detail for CABG",
    ],
    createdAt: "2026-06-01",
  },
];

// ── Prescriptions ──
export const prescriptions: Prescription[] = [
  {
    id: "rx01",
    patientId: "p04",
    patientName: "Robert Kim",
    medication: "Atorvastatin",
    dosage: "20mg",
    frequency: "Once daily",
    duration: "90 days",
    prescribedBy: "Dr. Patel",
    prescribedDate: "2026-06-05",
    status: "active",
    refillsRemaining: 2,
    pharmacy: "CVS Pharmacy #4421",
    notes: "Take in the evening. Lipid panel in 12 weeks.",
    createdAt: "2026-06-05",
  },
  {
    id: "rx02",
    patientId: "p02",
    patientName: "James Walker",
    medication: "Symbicort",
    dosage: "160/4.5mcg",
    frequency: "Twice daily",
    duration: "90 days",
    prescribedBy: "Dr. Patel",
    prescribedDate: "2026-05-25",
    status: "active",
    refillsRemaining: 3,
    pharmacy: "Walgreens #8812",
    notes: "Rinse mouth after use. Use spacer.",
    createdAt: "2026-05-25",
  },
  {
    id: "rx03",
    patientId: "p04",
    patientName: "Robert Kim",
    medication: "Aspirin",
    dosage: "81mg",
    frequency: "Once daily",
    duration: "90 days",
    prescribedBy: "Dr. Patel",
    prescribedDate: "2026-06-05",
    status: "active",
    refillsRemaining: 3,
    pharmacy: "CVS Pharmacy #4421",
    notes: "Enteric coated. Take with food.",
    createdAt: "2026-06-05",
  },
  {
    id: "rx04",
    patientId: "p06",
    patientName: "David Thompson",
    medication: "Cyclobenzaprine",
    dosage: "5mg",
    frequency: "At bedtime",
    duration: "30 days",
    prescribedBy: "Dr. Osei",
    prescribedDate: "2026-05-15",
    status: "active",
    refillsRemaining: 1,
    pharmacy: "Rite Aid #2256",
    notes: "Taper to half dose after 2 weeks if pain improved.",
    createdAt: "2026-05-15",
  },
  {
    id: "rx05",
    patientId: "p09",
    patientName: "Lily Chen",
    medication: "Fluticasone",
    dosage: "44mcg",
    frequency: "Twice daily",
    duration: "90 days",
    prescribedBy: "Dr. Osei",
    prescribedDate: "2026-06-03",
    status: "active",
    refillsRemaining: 3,
    pharmacy: "Walgreens #8812",
    notes: "Use with spacer. Administer before brushing teeth.",
    createdAt: "2026-06-03",
  },
  {
    id: "rx06",
    patientId: "p01",
    patientName: "Maria Santos",
    medication: "Metformin",
    dosage: "1000mg",
    frequency: "Twice daily",
    duration: "90 days",
    prescribedBy: "Dr. Chen",
    prescribedDate: "2026-06-01",
    status: "active",
    refillsRemaining: 3,
    pharmacy: "CVS Pharmacy #4421",
    notes: "Take with meals. Monitor blood glucose daily.",
    createdAt: "2026-06-01",
  },
  {
    id: "rx07",
    patientId: "p01",
    patientName: "Maria Santos",
    medication: "Lisinopril",
    dosage: "10mg",
    frequency: "Once daily",
    duration: "90 days",
    prescribedBy: "Dr. Chen",
    prescribedDate: "2026-06-01",
    status: "active",
    refillsRemaining: 3,
    pharmacy: "CVS Pharmacy #4421",
    notes: "Monitor BP weekly. Avoid potassium supplements.",
    createdAt: "2026-06-01",
  },
  {
    id: "rx08",
    patientId: "p02",
    patientName: "James Walker",
    medication: "Prednisone",
    dosage: "40mg",
    frequency: "Once daily",
    duration: "5 days (taper)",
    prescribedBy: "Dr. Patel",
    prescribedDate: "2026-05-25",
    status: "completed",
    refillsRemaining: 0,
    pharmacy: "Walgreens #8812",
    notes: "Taper: 40mg x1 day, 30mg x1, 20mg x1, 10mg x1, 5mg x1. Take with food.",
    createdAt: "2026-05-25",
  },
  {
    id: "rx09",
    patientId: "p03",
    patientName: "Elena Rodriguez",
    medication: "Escitalopram",
    dosage: "10mg",
    frequency: "Once daily",
    duration: "90 days",
    prescribedBy: "Dr. Chen",
    prescribedDate: "2026-05-28",
    status: "active",
    refillsRemaining: 2,
    pharmacy: "Rite Aid #2256",
    notes: "Take in the morning. Do not discontinue abruptly.",
    createdAt: "2026-05-28",
  },
  {
    id: "rx10",
    patientId: "p08",
    patientName: "William Harrison",
    medication: "Tiotropium",
    dosage: "18mcg",
    frequency: "Once daily",
    duration: "90 days",
    prescribedBy: "Dr. Patel",
    prescribedDate: "2026-06-02",
    status: "active",
    refillsRemaining: 3,
    pharmacy: "CVS Pharmacy #4421",
    notes: "Use HandiHaler device. Do not swallow capsule.",
    createdAt: "2026-06-02",
  },
  {
    id: "rx11",
    patientId: "p08",
    patientName: "William Harrison",
    medication: "Albuterol HFA",
    dosage: "90mcg",
    frequency: "As needed",
    duration: "30 days",
    prescribedBy: "Dr. Patel",
    prescribedDate: "2026-06-02",
    status: "active",
    refillsRemaining: 3,
    pharmacy: "CVS Pharmacy #4421",
    notes: "Use for acute shortness of breath. 2 puffs as needed.",
    createdAt: "2026-06-02",
  },
  {
    id: "rx12",
    patientId: "p07",
    patientName: "Amara Okafor",
    medication: "Ferrous Sulfate",
    dosage: "325mg",
    frequency: "Once daily",
    duration: "90 days",
    prescribedBy: "Dr. Chen",
    prescribedDate: "2026-06-09",
    status: "active",
    refillsRemaining: 3,
    pharmacy: "Walgreens #8812",
    notes: "Take with vitamin C for absorption. May cause constipation.",
    createdAt: "2026-06-09",
  },
  {
    id: "rx13",
    patientId: "p10",
    patientName: "Michael Patel",
    medication: "Famotidine",
    dosage: "20mg",
    frequency: "At bedtime",
    duration: "30 days",
    prescribedBy: "Dr. Chen",
    prescribedDate: "2026-06-06",
    status: "active",
    refillsRemaining: 2,
    pharmacy: "Rite Aid #2256",
    notes: "Take 30 minutes before bedtime. Avoid late meals.",
    createdAt: "2026-06-06",
  },
];

// ── Clinic Metrics ──
export const metrics: HealthcareMetric[] = [
  {
    id: "m01",
    label: "Active Patients",
    value: 2847,
    unit: "patients",
    change: 4.2,
    period: "month",
    trend: "up",
    updatedAt: "2026-06-09",
  },
  {
    id: "m02",
    label: "Appointments Today",
    value: 42,
    unit: "appointments",
    change: -3.1,
    period: "today",
    trend: "down",
    updatedAt: "2026-06-09",
  },
  {
    id: "m03",
    label: "AI Notes Generated",
    value: 1893,
    unit: "notes",
    change: 12.8,
    period: "month",
    trend: "up",
    updatedAt: "2026-06-09",
  },
  {
    id: "m04",
    label: "Average Wait Time",
    value: 8.4,
    unit: "minutes",
    change: -15.2,
    period: "month",
    trend: "down",
    updatedAt: "2026-06-09",
  },
  {
    id: "m05",
    label: "Intake Completion Rate",
    value: 92,
    unit: "%",
    change: 5.7,
    period: "month",
    trend: "up",
    updatedAt: "2026-06-09",
  },
  {
    id: "m06",
    label: "Prescriptions Issued",
    value: 421,
    unit: "prescriptions",
    change: 2.3,
    period: "month",
    trend: "up",
    updatedAt: "2026-06-09",
  },
];
